build: add --strict_front_matter to build invocation
Should help catch issues like those in #1042, which didn't cause the CI
to fail.

```bash
bundle exec jekyll server --future --drafts --unpublished --incremental --strict_front_matter
...
 Incremental build: enabled
      Generating...
             Error: YAML Exception reading /Users/michael/bitcoincore.org/_posts/en/posts/2024-06-10-disclose-bip70-crash.md: (<unknown>): mapping values are not allowed in this context at line 2 column 18
                    ------------------------------------------------
```